version: '3.8'

services:
  golang-auth:
    build: ./
    command: ./golang-auth
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5444:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5